# Generated by Django 6.0.1 on 2026-01-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_blog_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoPost',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
