# Generated by Django 5.2.8 on 2026-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_add_cottage_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_photo',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
