# Generated by Django 5.2.8 on 2026-02-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_update_product_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='karaoke_en',
            field=models.TextField(blank=True, null=True, verbose_name='Karaoke'),
        ),
        migrations.AddField(
            model_name='product',
            name='karaoke_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Караоке'),
        ),
        migrations.AddField(
            model_name='product',
            name='karaoke_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Karaoke'),
        ),
        migrations.AlterField(
            model_name='product',
            name='beds',
            field=models.TextField(blank=True, null=True, verbose_name='Кровати'),
        ),
        migrations.AlterField(
            model_name='product',
            name='beds_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
