# Generated by Django 5.2.8 on 2026-02-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_add_more_blog_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя / Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email / Pochta')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон / Telefon')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема / Mavzu')),
                ('message', models.TextField(verbose_name='Сообщение / Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name="Прочитано / O'qilgan")),
            ],
            options={
                'verbose_name': "Contact / Bog'lanish",
                'verbose_name_plural': "Contacts / Bog'lanishlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
