# Generated by Django 5.2.8 on 2026-03-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bedrooms_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bedrooms_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bedrooms_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guests_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guests_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guests_uz',
        ),
        migrations.AddField(
            model_name='product',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='Санузлы'),
        ),
        migrations.AddField(
            model_name='product',
            name='floors',
            field=models.IntegerField(default=1, verbose_name='Этажность'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_fireplace',
            field=models.BooleanField(default=False, verbose_name='Камин'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_tapchan',
            field=models.BooleanField(default=False, verbose_name='Тапчан'),
        ),
        migrations.AddField(
            model_name='product',
            name='land_area',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Площадь участка (соток)'),
        ),
        migrations.AddField(
            model_name='product',
            name='parking_places',
            field=models.IntegerField(default=0, verbose_name='Парковочных мест'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_area',
            field=models.IntegerField(default=0, verbose_name='Площадь дома (м²)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bedrooms',
            field=models.IntegerField(default=4, verbose_name='Спальни'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_guests',
            field=models.IntegerField(default=12, verbose_name='Макс. гостей'),
        ),
    ]
