# Generated by Django 5.2.8 on 2026-03-31 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_populate_25_cottages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barbecue_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barbecue_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barbecue_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='billiards_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='billiards_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='billiards_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chess_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chess_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chess_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='computer_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='computer_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='computer_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gas_stove_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gas_stove_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gas_stove_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hammam_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hammam_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hammam_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hookah_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hookah_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hookah_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='indoor_pool_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='indoor_pool_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='indoor_pool_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='iron_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='iron_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='iron_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='jacuzzi_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='jacuzzi_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='jacuzzi_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='karaoke_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='karaoke_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='karaoke_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kitchen_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kitchen_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kitchen_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mangal_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mangal_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mangal_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='microwave_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='microwave_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='microwave_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='outdoor_pool_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='outdoor_pool_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='outdoor_pool_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='playstation_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='playstation_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='playstation_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='refrigerator_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='refrigerator_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='refrigerator_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salt_room_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salt_room_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salt_room_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sauna_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sauna_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sauna_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summer_kitchen_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summer_kitchen_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summer_kitchen_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='table_tennis_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='table_tennis_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='table_tennis_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tv_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tv_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tv_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='washing_machine_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='washing_machine_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='washing_machine_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wifi_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wifi_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wifi_uz',
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='product',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_barbecue',
            field=models.BooleanField(default=False, verbose_name='Barbecue'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_billiards',
            field=models.BooleanField(default=False, verbose_name='Billiards'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_chess',
            field=models.BooleanField(default=False, verbose_name='Chess'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_computer',
            field=models.BooleanField(default=False, verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_gas_stove',
            field=models.BooleanField(default=False, verbose_name='Gas Stove'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_hammam',
            field=models.BooleanField(default=False, verbose_name='Hammam'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_hookah',
            field=models.BooleanField(default=False, verbose_name='Hookah'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_indoor_pool',
            field=models.BooleanField(default=False, verbose_name='Indoor Pool'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_iron',
            field=models.BooleanField(default=False, verbose_name='Iron'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_jacuzzi',
            field=models.BooleanField(default=False, verbose_name='Jacuzzi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_karaoke',
            field=models.BooleanField(default=False, verbose_name='Karaoke'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_kitchen',
            field=models.BooleanField(default=False, verbose_name='Kitchen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_mangal',
            field=models.BooleanField(default=False, verbose_name='BBQ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_microwave',
            field=models.BooleanField(default=False, verbose_name='Microwave'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_outdoor_pool',
            field=models.BooleanField(default=False, verbose_name='Outdoor Pool'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_playstation',
            field=models.BooleanField(default=False, verbose_name='PlayStation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_refrigerator',
            field=models.BooleanField(default=False, verbose_name='Refrigerator'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_salt_room',
            field=models.BooleanField(default=False, verbose_name='Salt Room'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_sauna',
            field=models.BooleanField(default=False, verbose_name='Sauna'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_summer_kitchen',
            field=models.BooleanField(default=False, verbose_name='Summer Kitchen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_table_tennis',
            field=models.BooleanField(default=False, verbose_name='Table Tennis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_tv',
            field=models.BooleanField(default=False, verbose_name='TV'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_washing_machine',
            field=models.BooleanField(default=False, verbose_name='Washing Machine'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='indoor_pool_heated',
            field=models.BooleanField(default=False, verbose_name='Indoor Pool Heated'),
        ),
        migrations.AlterField(
            model_name='product',
            name='indoor_pool_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indoor Pool Length'),
        ),
        migrations.AlterField(
            model_name='product',
            name='indoor_pool_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indoor Pool Width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='outdoor_pool_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Outdoor Pool Length'),
        ),
        migrations.AlterField(
            model_name='product',
            name='outdoor_pool_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Outdoor Pool Width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sauna_daily_limit_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sauna Daily Limit (Hours)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sauna_rule_en',
            field=models.TextField(blank=True, null=True, verbose_name='Sauna rules (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sauna_rule_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Правила сауны (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sauna_rule_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Sauna qoidalari (UZ)'),
        ),
        migrations.CreateModel(
            name='CottageAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_busy', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='gallery.product')),
            ],
            options={
                'verbose_name': 'Cottage Availability / Bron qilingan kunlar',
                'verbose_name_plural': 'Cottages Availability / Bron qilingan kunlar',
                'ordering': ['date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
