# Generated by Django 5.2.8 on 2026-04-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_announcement_employee_payment_service_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Amirsoy', 'Amirsoy'), ('Charvak', 'Charvak'), ('Chimgan', 'Chimgan'), ('Oqtosh', 'Oqtosh'), ('Parkent', 'Parkent'), ('Sijjak', 'Sijjak')], default='Cottage', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.product')),
            ],
        ),
    ]
