# Generated by Django 5.2.8 on 2026-04-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_product_rating_alter_product_category_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcement_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.announcement')),
            ],
        ),
    ]
