# Generated by Django 5.2.8 on 2026-04-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_announcement_photo_contact_status_announcementimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='facebook_link',
            field=models.URLField(blank=True, default='https://facebook.com/dachago', null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram_link',
            field=models.URLField(blank=True, default='https://instagram.com/dachago', null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='telegram_link',
            field=models.URLField(blank=True, default='https://t.me/dachago', null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='youtube_link',
            field=models.URLField(blank=True, default='https://youtube.com/dachago', null=True),
        ),
    ]
